package com.ablevm.cfe.backend.apirest.zona.dominio;
// default package
// Generated 26 jul 2020 1:13:31 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name = "zona", catalog = "mydb")
public class Zona implements java.io.Serializable {

	private int idZon;
	private String nomZon;


	public Zona() {
	}

	public Zona(int idZon, String nomZon) {
		this.idZon = idZon;
		this.nomZon = nomZon;
	}


	@Id

	@Column(name = "Id_Zon", unique = true, nullable = false)
	public int getIdZon() {
		return this.idZon;
	}

	public void setIdZon(int idZon) {
		this.idZon = idZon;
	}

	@Column(name = "Nom_Zon", nullable = false, length = 45)
	public String getNomZon() {
		return this.nomZon;
	}

	public void setNomZon(String nomZon) {
		this.nomZon = nomZon;
	}



}
