package com.ablevm.cfe.backend.apirest.material.dominio;
// default package
// Generated 26 jul 2020 1:13:31 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", catalog = "mydb")
public class Material implements java.io.Serializable {

	private int idMat;
	private String nomMat;
	private String uniMat;
	private String descMat;

	public Material() {
	}

	public Material(int idMat, String nomMat, String uniMat) {
		this.idMat = idMat;
		this.nomMat = nomMat;
		this.uniMat = uniMat;
	}

	public Material(int idMat, String nomMat, String uniMat, String descMat) {
		this.idMat = idMat;
		this.nomMat = nomMat;
		this.uniMat = uniMat;
		this.descMat = descMat;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Id_Mat", unique = true, nullable = false)
	public int getIdMat() {
		return this.idMat;
	}

	public void setIdMat(int idMat) {
		this.idMat = idMat;
	}

	@Column(name = "Nom_Mat", nullable = false, length = 45)
	public String getNomMat() {
		return this.nomMat;
	}

	public void setNomMat(String nomMat) {
		this.nomMat = nomMat;
	}

	@Column(name = "Uni_Mat", nullable = false, length = 15)
	public String getUniMat() {
		return this.uniMat;
	}

	public void setUniMat(String uniMat) {
		this.uniMat = uniMat;
	}

	@Column(name = "Desc_Mat", length = 45)
	public String getDescMat() {
		return this.descMat;
	}

	public void setDescMat(String descMat) {
		this.descMat = descMat;
	}


}
