package com.ablevm.cfe.backend.apirest.agencia.dominio;
// default package
// Generated 26 jul 2020 1:13:31 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;



/**
 * Agencia generated by hbm2java
 */
@Entity
@Table(name = "agencia", catalog = "mydb", uniqueConstraints = @UniqueConstraint(columnNames = "Nom_Age"))
public class Agencia implements java.io.Serializable {

	private int idAge;
	private String nomAge;


	public Agencia() {
	}

	public Agencia(int idAge, String nomAge) {
		this.idAge = idAge;
		this.nomAge = nomAge;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Age", unique = true, nullable = false)
	public int getIdAge() {
		return this.idAge;
	}

	public void setIdAge(int idAge) {
		this.idAge = idAge;
	}

	@Column(name = "Nom_Age", unique = true, nullable = false, length = 45)
	public String getNomAge() {
		return this.nomAge;
	}

	public void setNomAge(String nomAge) {
		this.nomAge = nomAge;
	}


}
