package com.ablevm.cfe.backend.apirest.orden.dominio;
// default package
// Generated 26 jul 2020 1:46:45 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.ablevm.cfe.backend.apirest.agencia.dominio.Agencia;
import com.ablevm.cfe.backend.apirest.cliente.dominio.Cliente;
import com.ablevm.cfe.backend.apirest.trabajo.dominio.Trabajo;
import com.ablevm.cfe.backend.apirest.ubicacion.dominio.Ubicacion;
import com.ablevm.cfe.backend.apirest.usuario.dominio.Usuario;
import com.ablevm.cfe.backend.apirest.zona.dominio.Zona;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Orden generated by hbm2java
 */
@Entity
@Table(name = "orden", catalog = "mydb", uniqueConstraints = { @UniqueConstraint(columnNames = "Id_Ord"),
		@UniqueConstraint(columnNames = "No_Ord") })
public class Orden implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Agencia agencia;
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Cliente cliente;
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Trabajo trabajo;
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Ubicacion ubicacion;
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Usuario usuario;
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Zona zona;
	private String idOrd;
	private String noOrd;
	private Date fechOrd;
	private String rpuOrd;
	private String ncuenOrd;
	private int tarifaOrd;
	private String t02Ord;
	private String giroOrd;
	private String hilosOrd;
	private String faseOrd;
	private String anomOrd;
	private String medIqzOrd;
	private String medDerOrd;
	private Date horaIncOrd;
	private Date horaFinOrd;
	private String atendOrd;
	private String resibOrd;
	private String rpeOrd;
	private String identNOrd;

	public Orden() {
	}
	

	public Orden( String idOrd, Agencia agencia, Trabajo trabajo, Usuario usuario, Zona zona, Date fechOrd, String rpuOrd,
			String ncuenOrd, int tarifaOrd, String atendOrd) {
		this.idOrd = idOrd;
		this.agencia = agencia;
		this.trabajo = trabajo;
		this.usuario = usuario;
		this.zona = zona;
		this.fechOrd = fechOrd;
		this.rpuOrd = rpuOrd;
		this.ncuenOrd = ncuenOrd;
		this.tarifaOrd = tarifaOrd;
		this.atendOrd = atendOrd;
	}

	/*public Orden(OrdenId id, Agencia agencia, Trabajo trabajo, Usuario usuario, Zona zona, Date fechOrd, String rpuOrd,
			String ncuenOrd, int tarifaOrd, String atendOrd) {
		this.id = id;
		this.agencia = agencia;
		this.trabajo = trabajo;
		this.usuario = usuario;
		this.zona = zona;
		this.fechOrd = fechOrd;
		this.rpuOrd = rpuOrd;
		this.ncuenOrd = ncuenOrd;
		this.tarifaOrd = tarifaOrd;
		this.atendOrd = atendOrd;
	}*/
	
	public Orden( String idOrd,Agencia agencia,Cliente cliente,Trabajo trabajo, Ubicacion ubicacion, Usuario usuario,
			Zona zona,String noOrd, Date fechOrd, String rpuOrd, String ncuenOrd, int tarifaOrd, String t02Ord,
	String giroOrd, String hilosOrd, String faseOrd, String anomOrd, String medIqzOrd, String medDerOrd,
	Date horaIncOrd, Date horaFinOrd, String atendOrd, String resibOrd, String rpeOrd, String identNOrd) {
		this.idOrd = idOrd;
		this.agencia = agencia;
		this.cliente = cliente;
		this.trabajo = trabajo;
		this.ubicacion = ubicacion;
		this.usuario = usuario;
		this.zona = zona;
this.noOrd = noOrd;
this.fechOrd = fechOrd;
this.rpuOrd = rpuOrd;
this.ncuenOrd = ncuenOrd;
this.tarifaOrd = tarifaOrd;
this.t02Ord = t02Ord;
this.giroOrd = giroOrd;
this.hilosOrd = hilosOrd;
this.faseOrd = faseOrd;
this.anomOrd = anomOrd;
this.medIqzOrd = medIqzOrd;
this.medDerOrd = medDerOrd;
this.horaIncOrd = horaIncOrd;
this.horaFinOrd = horaFinOrd;
this.atendOrd = atendOrd;
this.resibOrd = resibOrd;
this.rpeOrd = rpeOrd;
this.identNOrd = identNOrd;
}

	/*public Orden(OrdenId id, Agencia agencia, Cliente cliente, Trabajo trabajo, Ubicacion ubicacion, Usuario usuario,
			Zona zona, String noOrd, Date fechOrd, String rpuOrd, String ncuenOrd, int tarifaOrd, String t02Ord,
			String giroOrd, String hilosOrd, String faseOrd, String anomOrd, String medIqzOrd, String medDerOrd,
			Date horaIncOrd, Date horaFinOrd, String atendOrd, String resibOrd, String rpeOrd, String identNOrd) {
		this.id = id;
		this.agencia = agencia;
		this.cliente = cliente;
		this.trabajo = trabajo;
		this.ubicacion = ubicacion;
		this.usuario = usuario;
		this.zona = zona;
		this.noOrd = noOrd;
		this.fechOrd = fechOrd;
		this.rpuOrd = rpuOrd;
		this.ncuenOrd = ncuenOrd;
		this.tarifaOrd = tarifaOrd;
		this.t02Ord = t02Ord;
		this.giroOrd = giroOrd;
		this.hilosOrd = hilosOrd;
		this.faseOrd = faseOrd;
		this.anomOrd = anomOrd;
		this.medIqzOrd = medIqzOrd;
		this.medDerOrd = medDerOrd;
		this.horaIncOrd = horaIncOrd;
		this.horaFinOrd = horaFinOrd;
		this.atendOrd = atendOrd;
		this.resibOrd = resibOrd;
		this.rpeOrd = rpeOrd;
		this.identNOrd = identNOrd;
	}*/

	@Id
	@Column(name = "Id_Ord", unique = true, nullable = false)
	public String getIdOrd() {
		return this.idOrd;
	}

	public void setIdOrd(String idOrd) {
		this.idOrd = idOrd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Agencia_Id_Age", nullable = false)
	public Agencia getAgencia() {
		return this.agencia;
	}

	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cliente_Id_Client")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Trabajo_Id_Trab", nullable = false, insertable = false, updatable = false)
	public Trabajo getTrabajo() {
		return this.trabajo;
	}

	public void setTrabajo(Trabajo trabajo) {
		this.trabajo = trabajo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ubicacion_Id_Ubi")
	public Ubicacion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion ubicacion) {
		this.ubicacion = ubicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Usuario_Id_Usu", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Zona_Id_Zon", nullable = false)
	public Zona getZona() {
		return this.zona;
	}

	public void setZona(Zona zona) {
		this.zona = zona;
	}

	@Column(name = "No_Ord", unique = true, length = 5)
	public String getNoOrd() {
		return this.noOrd;
	}

	public void setNoOrd(String noOrd) {
		this.noOrd = noOrd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fech_Ord", nullable = false, length = 10)
	public Date getFechOrd() {
		return this.fechOrd;
	}

	public void setFechOrd(Date fechOrd) {
		this.fechOrd = fechOrd;
	}

	@Column(name = "Rpu_Ord", nullable = false, length = 15)
	public String getRpuOrd() {
		return this.rpuOrd;
	}

	public void setRpuOrd(String rpuOrd) {
		this.rpuOrd = rpuOrd;
	}

	@Column(name = "NCuen_Ord", nullable = false, length = 17)
	public String getNcuenOrd() {
		return this.ncuenOrd;
	}

	public void setNcuenOrd(String ncuenOrd) {
		this.ncuenOrd = ncuenOrd;
	}

	@Column(name = "Tarifa_Ord", nullable = false)
	public int getTarifaOrd() {
		return this.tarifaOrd;
	}

	public void setTarifaOrd(int tarifaOrd) {
		this.tarifaOrd = tarifaOrd;
	}

	@Column(name = "T02_Ord", length = 4)
	public String getT02Ord() {
		return this.t02Ord;
	}

	public void setT02Ord(String t02Ord) {
		this.t02Ord = t02Ord;
	}

	@Column(name = "Giro_Ord", length = 4)
	public String getGiroOrd() {
		return this.giroOrd;
	}

	public void setGiroOrd(String giroOrd) {
		this.giroOrd = giroOrd;
	}

	@Column(name = "Hilos_Ord", length = 2)
	public String getHilosOrd() {
		return this.hilosOrd;
	}

	public void setHilosOrd(String hilosOrd) {
		this.hilosOrd = hilosOrd;
	}

	@Column(name = "Fase_Ord", length = 2)
	public String getFaseOrd() {
		return this.faseOrd;
	}

	public void setFaseOrd(String faseOrd) {
		this.faseOrd = faseOrd;
	}

	@Column(name = "Anom_Ord", length = 40)
	public String getAnomOrd() {
		return this.anomOrd;
	}

	public void setAnomOrd(String anomOrd) {
		this.anomOrd = anomOrd;
	}

	@Column(name = "MedIqz_Ord", length = 10)
	public String getMedIqzOrd() {
		return this.medIqzOrd;
	}

	public void setMedIqzOrd(String medIqzOrd) {
		this.medIqzOrd = medIqzOrd;
	}

	@Column(name = "MedDer_Ord", length = 10)
	public String getMedDerOrd() {
		return this.medDerOrd;
	}

	public void setMedDerOrd(String medDerOrd) {
		this.medDerOrd = medDerOrd;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HoraInc_Ord", length = 8)
	public Date getHoraIncOrd() {
		return this.horaIncOrd;
	}

	public void setHoraIncOrd(Date horaIncOrd) {
		this.horaIncOrd = horaIncOrd;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HoraFin_Ord", length = 8)
	public Date getHoraFinOrd() {
		return this.horaFinOrd;
	}

	public void setHoraFinOrd(Date horaFinOrd) {
		this.horaFinOrd = horaFinOrd;
	}

	@Column(name = "Atend_Ord", nullable = false, length = 45)
	public String getAtendOrd() {
		return this.atendOrd;
	}

	public void setAtendOrd(String atendOrd) {
		this.atendOrd = atendOrd;
	}

	@Column(name = "Resib_Ord", length = 45)
	public String getResibOrd() {
		return this.resibOrd;
	}

	public void setResibOrd(String resibOrd) {
		this.resibOrd = resibOrd;
	}

	@Column(name = "Rpe_Ord", length = 10)
	public String getRpeOrd() {
		return this.rpeOrd;
	}

	public void setRpeOrd(String rpeOrd) {
		this.rpeOrd = rpeOrd;
	}

	@Column(name = "IdentN_Ord", length = 10)
	public String getIdentNOrd() {
		return this.identNOrd;
	}

	public void setIdentNOrd(String identNOrd) {
		this.identNOrd = identNOrd;
	}

}
