package com.ablevm.cfe.backend.apirest.role.dominio;
// default package
// Generated 26 jul 2020 13:08:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.ablevm.cfe.backend.apirest.usuario.dominio.Usuario;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "mydb")
public class Role implements java.io.Serializable {

	private Integer idRole;
	private String nomRole;
	private String descRole;
	@JsonIgnore
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Role() {
	}

	public Role(String nomRole, String descRole) {
		this.nomRole = nomRole;
		this.descRole = descRole;
	}

	public Role(String nomRole, String descRole, Set<Usuario> usuarios) {
		this.nomRole = nomRole;
		this.descRole = descRole;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_Role", unique = true, nullable = false)
	public Integer getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	@Column(name = "Nom_Role", nullable = false, length = 16)
	public String getNomRole() {
		return this.nomRole;
	}

	public void setNomRole(String nomRole) {
		this.nomRole = nomRole;
	}

	@Column(name = "Desc_Role", nullable = false, length = 45)
	public String getDescRole() {
		return this.descRole;
	}

	public void setDescRole(String descRole) {
		this.descRole = descRole;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_has_role", catalog = "mydb", joinColumns = {
			@JoinColumn(name = "Role_Id_Role", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Usuario_Id_Usu", nullable = false, updatable = false) })
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
