package com.ablevm.cfe.backend.apirest.medidor.dominio;
// default package
// Generated 26 jul 2020 1:13:31 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.ablevm.cfe.backend.apirest.orden.dominio.Orden;

/**
 * Medidori generated by hbm2java
 */
@Entity
@Table(name = "medidori", catalog = "mydb")
public class Medidori implements java.io.Serializable {

	private int idMedI;
	private Orden orden;
	private String nsMedI;
	private String lecMedI;
	private String noCarMedI;
	private String codMedI;
	private String codLotMedI;
	private String multMedI;
	private String noSeIntMedI;

	public Medidori() {
	}

	public Medidori(int idMedI, Orden orden, String nsMedI, String lecMedI) {
		this.idMedI = idMedI;
		this.orden = orden;
		this.nsMedI = nsMedI;
		this.lecMedI = lecMedI;
	}

	public Medidori(int idMedI, Orden orden, String nsMedI, String lecMedI, String noCarMedI, String codMedI,
			String codLotMedI, String multMedI, String noSeIntMedI) {
		this.idMedI = idMedI;
		this.orden = orden;
		this.nsMedI = nsMedI;
		this.lecMedI = lecMedI;
		this.noCarMedI = noCarMedI;
		this.codMedI = codMedI;
		this.codLotMedI = codLotMedI;
		this.multMedI = multMedI;
		this.noSeIntMedI = noSeIntMedI;
	}

	@Id

	@Column(name = "Id_MedI", unique = true, nullable = false)
	public int getIdMedI() {
		return this.idMedI;
	}

	public void setIdMedI(int idMedI) {
		this.idMedI = idMedI;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Orden_Id_Ord", nullable = false)
	public Orden getOrden() {
		return this.orden;
	}

	public void setOrden(Orden orden) {
		this.orden = orden;
	}

	@Column(name = "Ns_MedI", nullable = false, length = 7)
	public String getNsMedI() {
		return this.nsMedI;
	}

	public void setNsMedI(String nsMedI) {
		this.nsMedI = nsMedI;
	}

	@Column(name = "Lec_MedI", nullable = false, length = 4)
	public String getLecMedI() {
		return this.lecMedI;
	}

	public void setLecMedI(String lecMedI) {
		this.lecMedI = lecMedI;
	}

	@Column(name = "NoCar_MedI", length = 4)
	public String getNoCarMedI() {
		return this.noCarMedI;
	}

	public void setNoCarMedI(String noCarMedI) {
		this.noCarMedI = noCarMedI;
	}

	@Column(name = "Cod_MedI", length = 10)
	public String getCodMedI() {
		return this.codMedI;
	}

	public void setCodMedI(String codMedI) {
		this.codMedI = codMedI;
	}

	@Column(name = "CodLot_MedI", length = 10)
	public String getCodLotMedI() {
		return this.codLotMedI;
	}

	public void setCodLotMedI(String codLotMedI) {
		this.codLotMedI = codLotMedI;
	}

	@Column(name = "Mult_MedI", length = 10)
	public String getMultMedI() {
		return this.multMedI;
	}

	public void setMultMedI(String multMedI) {
		this.multMedI = multMedI;
	}

	@Column(name = "NoSeInt_MedI", length = 10)
	public String getNoSeIntMedI() {
		return this.noSeIntMedI;
	}

	public void setNoSeIntMedI(String noSeIntMedI) {
		this.noSeIntMedI = noSeIntMedI;
	}

}
