package com.ablevm.cfe.backend.apirest.medidor.dominio;
// default package
// Generated 26 jul 2020 1:13:31 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.ablevm.cfe.backend.apirest.orden.dominio.Orden;

/**
 * Medidorr generated by hbm2java
 */
@Entity
@Table(name = "medidorr", catalog = "mydb")
public class Medidorr implements java.io.Serializable {

	private int idMedR;
	private Orden orden;
	private String nsMedR;
	private String lecMedR;
	private String noCarMedR;
	private String codMedR;
	private String codLotMedR;
	private String multMedR;
	private String noSeIntMedR;

	public Medidorr() {
	}

	public Medidorr(int idMedR, Orden orden, String nsMedR, String lecMedR) {
		this.idMedR = idMedR;
		this.orden = orden;
		this.nsMedR = nsMedR;
		this.lecMedR = lecMedR;
	}

	public Medidorr(int idMedR, Orden orden, String nsMedR, String lecMedR, String noCarMedR, String codMedR,
			String codLotMedR, String multMedR, String noSeIntMedR) {
		this.idMedR = idMedR;
		this.orden = orden;
		this.nsMedR = nsMedR;
		this.lecMedR = lecMedR;
		this.noCarMedR = noCarMedR;
		this.codMedR = codMedR;
		this.codLotMedR = codLotMedR;
		this.multMedR = multMedR;
		this.noSeIntMedR = noSeIntMedR;
	}

	@Id

	@Column(name = "Id_MedR", unique = true, nullable = false)
	public int getIdMedR() {
		return this.idMedR;
	}

	public void setIdMedR(int idMedR) {
		this.idMedR = idMedR;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Orden_Id_Ord", nullable = false)
	public Orden getOrden() {
		return this.orden;
	}

	public void setOrden(Orden orden) {
		this.orden = orden;
	}

	@Column(name = "Ns_MedR", nullable = false, length = 7)
	public String getNsMedR() {
		return this.nsMedR;
	}

	public void setNsMedR(String nsMedR) {
		this.nsMedR = nsMedR;
	}

	@Column(name = "Lec_MedR", nullable = false, length = 4)
	public String getLecMedR() {
		return this.lecMedR;
	}

	public void setLecMedR(String lecMedR) {
		this.lecMedR = lecMedR;
	}

	@Column(name = "NoCar_MedR", length = 4)
	public String getNoCarMedR() {
		return this.noCarMedR;
	}

	public void setNoCarMedR(String noCarMedR) {
		this.noCarMedR = noCarMedR;
	}

	@Column(name = "Cod_MedR", length = 10)
	public String getCodMedR() {
		return this.codMedR;
	}

	public void setCodMedR(String codMedR) {
		this.codMedR = codMedR;
	}

	@Column(name = "CodLot_MedR", length = 10)
	public String getCodLotMedR() {
		return this.codLotMedR;
	}

	public void setCodLotMedR(String codLotMedR) {
		this.codLotMedR = codLotMedR;
	}

	@Column(name = "Mult_MedR", length = 10)
	public String getMultMedR() {
		return this.multMedR;
	}

	public void setMultMedR(String multMedR) {
		this.multMedR = multMedR;
	}

	@Column(name = "NoSeInt_MedR", length = 10)
	public String getNoSeIntMedR() {
		return this.noSeIntMedR;
	}

	public void setNoSeIntMedR(String noSeIntMedR) {
		this.noSeIntMedR = noSeIntMedR;
	}

}
