package com.ablevm.cfe.backend.apirest.usuario.dominio;
// default package
// Generated 26 jul 2020 13:18:50 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.ablevm.cfe.backend.apirest.orden.dominio.Orden;
import com.ablevm.cfe.backend.apirest.role.dominio.Role;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "mydb", uniqueConstraints = @UniqueConstraint(columnNames = "UserName_Usu"))
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "Id_Usu", unique = true, nullable = false, length = 10)
	private String idUsu;
	
	@Column(name = "UserName_Usu", unique = true, nullable = false, length = 10)
	private String userNameUsu;
	
	@Column(name = "Nom_Usu", nullable = false, length = 25)
	private String nomUsu;
	
	@Column(name = "ApPa_Usu", nullable = false, length = 15)
	private String apPaUsu;
	
	@Column(name = "ApMa_Usu", nullable = false, length = 15)
	private String apMaUsu;
	
	@Column(name = "Pass_Usu", nullable = false, length = 16)
	private String passUsu;
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	private Set<Orden> ordens = new HashSet<Orden>(0);
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_has_role", catalog = "mydb", joinColumns = {
			@JoinColumn(name = "Usuario_Id_Usu", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Role_Id_Role", nullable = false, updatable = false) })
	private Set<Role> roles;

	public Usuario() {
	}

	public Usuario(String idUsu, String userNameUsu, String nomUsu, String apPaUsu, String apMaUsu, String passUsu) {
		this.idUsu = idUsu;
		this.userNameUsu = userNameUsu;
		this.nomUsu = nomUsu;
		this.apPaUsu = apPaUsu;
		this.apMaUsu = apMaUsu;
		this.passUsu = passUsu;
	}

	public Usuario(String idUsu, String userNameUsu, String nomUsu, String apPaUsu, String apMaUsu, String passUsu,
			Set<Orden> ordens, Set<Role> roles) {
		this.idUsu = idUsu;
		this.userNameUsu = userNameUsu;
		this.nomUsu = nomUsu;
		this.apPaUsu = apPaUsu;
		this.apMaUsu = apMaUsu;
		this.passUsu = passUsu;
		this.ordens = ordens;
		this.roles = roles;
	}


	public String getIdUsu() {
		return this.idUsu;
	}

	public void setIdUsu(String idUsu) {
		this.idUsu = idUsu;
	}

	public String getUserNameUsu() {
		return this.userNameUsu;
	}

	public void setUserNameUsu(String userNameUsu) {
		this.userNameUsu = userNameUsu;
	}


	public String getNomUsu() {
		return this.nomUsu;
	}

	public void setNomUsu(String nomUsu) {
		this.nomUsu = nomUsu;
	}
	
	public String getApPaUsu() {
		return this.apPaUsu;
	}

	public void setApPaUsu(String apPaUsu) {
		this.apPaUsu = apPaUsu;
	}


	public String getApMaUsu() {
		return this.apMaUsu;
	}

	public void setApMaUsu(String apMaUsu) {
		this.apMaUsu = apMaUsu;
	}


	public String getPassUsu() {
		return this.passUsu;
	}

	public void setPassUsu(String passUsu) {
		this.passUsu = passUsu;
	}

	public Set<Orden> getOrdens() {
		return this.ordens;
	}

	public void setOrdens(Set<Orden> ordens) {
		this.ordens = ordens;
	}


	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
